apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backblaze-credentials
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: backblaze-credentials
  data:
  - secretKey: application-key-id
    remoteRef:
      key: /accounts/backblaze
      property: application-key-id
  - secretKey: application-key
    remoteRef:
      key: /accounts/backblaze
      property: application-key
  - secretKey: repo-password
    remoteRef:
      key: /accounts/backblaze
      property: repo-password
