- name: Start PXE server
  hosts: localhost
  roles:
    - pxe_server

- name: Provision bare metal machines
  hosts: metal
  gather_facts: false
  roles:
    - wake

- name: Enable wake-on-lan
  hosts: metal
  roles:
    - enable_wol
